Try to auto generate a PullRequest on success.

diff --git a/.github/workflows/ArtifactsUpload.yml b/.github/workflows/ArtifactsUpload.yml
--- a/.github/workflows/ArtifactsUpload.yml
+++ b/.github/workflows/ArtifactsUpload.yml
@@ -1091,3 +1091,51 @@ jobs:
       auto_tag: ${{ needs.Prepare.outputs.is_release_commit }}
       workflow: 'ArtifactUpload.yml'
     secrets: inherit
+
+  PullRequest:
+    name: Create Pull-Request
+    runs-on: 'ubuntu-24.04'
+    needs:
+      - Prepare
+      - Verify-Github
+      - Verify-pyTooling
+      - Inspect-single-file
+      - Inspect-single-file-in-directory
+      - Inspect-double-file-in-directory
+      - Inspect-triple-file-in-directory
+      - Inspect-double-file-in-deep-directory
+      - Inspect-single-directory
+      - Inspect-double-directory
+      - Inspect-unpredictable-wildcard
+      - Verify-9
+    if: needs.Prepare.outputs.is_release_tag == 'true'
+    permissions:
+      contents: write
+      actions:  write
+    defaults:
+      run:
+        shell: bash
+
+    steps:
+      - name: Create Pull-Request
+        run: |
+          set +e
+
+          ANSI_LIGHT_RED=$'\x1b[91m'
+          ANSI_LIGHT_GREEN=$'\x1b[92m'
+          ANSI_LIGHT_YELLOW=$'\x1b[93m'
+          ANSI_LIGHT_BLUE=$'\x1b[94m'
+          ANSI_NOCOLOR=$'\x1b[0m'
+
+          export GH_TOKEN=${{ github.token }}
+
+          title="Update v6 from ${{ needs.Prepare.outputs.version }}"
+
+          printf "Creating pull-request '${title}' ... "
+          gh pr create --title "${title}" --body "Auto generated"
+          if [[ $? -eq 0 ]]; then
+              printf "${ANSI_LIGHT_GREEN}[OK]${ANSI_NOCOLOR}\n"
+          else
+            printf "${ANSI_LIGHT_RED}[FAILED]${ANSI_NOCOLOR}\n"
+            printf "::error title=%s::%s\n" "GitHub PullRequest API" "Couldn't create pull-request."
+          fi
